# Generated by Django 3.0.6 on 2020-06-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категорія')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва товару')),
                ('old_price', models.CharField(max_length=150, verbose_name='Стара ціна')),
                ('new_price', models.CharField(max_length=150, verbose_name='Нова ціна')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('image_hover', models.ImageField(upload_to='', verbose_name='Картника по наведенню')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
