# Generated by Django 3.0.6 on 2020-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200613_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='Apple', max_length=150, verbose_name='Виробник'),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='Black', max_length=150, verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='item',
            name='diagonal',
            field=models.CharField(default="4,5'", max_length=150, verbose_name='Діагональ'),
        ),
    ]
