# Generated by Django 3.0.6 on 2020-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200613_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='diagonal',
            field=models.CharField(blank=True, default="4,5'", max_length=150, verbose_name='Діагональ'),
        ),
    ]
