# Generated by Django 3.0.6 on 2020-07-13 11:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0009_auto_20200629_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Відгук')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 11, 25, 13, 854768), verbose_name='Дата публікації')),
                ('reting', models.CharField(max_length=150, verbose_name='Рейтинг')),
                ('current_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='UserWishList',
        ),
    ]
