# Generated by Django 3.0.6 on 2020-07-13 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0010_auto_20200713_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreviews',
            options={'verbose_name': 'Відгук користувача', 'verbose_name_plural': 'Відгуки користувача'},
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 12, 0, 21, 517253), verbose_name='Дата публікації'),
        ),
    ]
